<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mqtt"
    nsURI="http://ns.tibco.com/bw/palette/mqtt" nsPrefix="mqtt">
  <eClassifiers xsi:type="ecore:EClass" name="MQTTPublishActivity">
    <eAnnotations source="dkactivityconfig">
      <details key="activitytype" value="Synchronous"/>
      <details key="schemaType" value="XSD Editor"/>
      <details key="schemaFile" value="/home/yogesh/work/bw6-workspace/MQTT/palette/design/plugins/com.bitzing.bw.palette.mqtt.design/schema/MQTTPublishActivitySchema.xsd"/>
      <details key="inputelementname" value="MQTTPublishActivityInput"/>
      <details key="outputelementname" value=""/>
      <details key="faultelementname" value="MQTTPublishActivityFault"/>
      <details key="helpdocuuid" value="27cb0b9b-a3bf-4abf-be44-e6629e0be180"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="dkcontrolconfig">
        <details key="sectionName" value="General"/>
        <details key="isRequired" value="true"/>
        <details key="label" value="Server URI"/>
        <details key="isModelProperty" value="true"/>
        <details key="control" value="TextBox"/>
        <details key="value" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="dkcontrolconfig">
        <details key="sectionName" value="General"/>
        <details key="isRequired" value="true"/>
        <details key="label" value="Client ID"/>
        <details key="isModelProperty" value="true"/>
        <details key="control" value="TextBox"/>
        <details key="value" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MQTTMessageSubscriber">
    <eAnnotations source="dkactivityconfig">
      <details key="activitytype" value="Process Starter"/>
      <details key="schemaType" value="XSD Editor"/>
      <details key="schemaFile" value="/home/yogesh/work/bw6-workspace/MQTT/palette/design/plugins/com.bitzing.bw.palette.mqtt.design/schema/MQTTMessageSubscriberSchema.xsd"/>
      <details key="inputelementname" value=""/>
      <details key="outputelementname" value="MQTTMessageSubscriberOutput"/>
      <details key="faultelementname" value=""/>
      <details key="helpdocuuid" value="b7ee18d0-6c98-4ccd-b7da-6c9ec428089e"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ServerURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="dkcontrolconfig">
        <details key="sectionName" value="General"/>
        <details key="isRequired" value="true"/>
        <details key="label" value="ServerURI"/>
        <details key="isModelProperty" value="true"/>
        <details key="control" value="TextBox"/>
        <details key="value" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ClientID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="dkcontrolconfig">
        <details key="sectionName" value="General"/>
        <details key="isRequired" value="true"/>
        <details key="label" value="clientID"/>
        <details key="isModelProperty" value="true"/>
        <details key="control" value="TextBox"/>
        <details key="value" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="dkcontrolconfig">
        <details key="sectionName" value="General"/>
        <details key="isRequired" value="true"/>
        <details key="label" value="Topic"/>
        <details key="isModelProperty" value="true"/>
        <details key="control" value="TextBox"/>
        <details key="value" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
