package com.bitzing.bw.palette.mqtt.runtime;

import com.tibco.neo.localized.BundleMessage;
import com.tibco.neo.localized.MessageBundle;

/**
 * A message bundle for this package.

 * THIS FILE WAS AUTOMATICALLY GENERATED BY A CONVERSION TOOL.
 * IF YOU EDIT IT, YOU MAY LOSE YOUR CHANGES.
 */
public class RuntimeMessageBundle extends MessageBundle 
{

    // Following member is accessed by MessageBundle.initializeMessages, do not remove!
    static public final String BUNDLE_NAME = "com.bitzing.bw.palette.mqtt.runtime.Resources"; //$NON-NLS-1$

    static {
        MessageBundle.initializeMessages(RuntimeMessageBundle.class);
    }
    public static BundleMessage DEBUG_PLUGIN_ACTIVITY_INPUT;
    public static BundleMessage DEBUG_PLUGIN_ACTIVITY_OUTPUT;
    public static BundleMessage ERROR_OCCURED_RETRIEVE_RESULT;
    public static BundleMessage ERROR_OCCURED_INVOKE_EXECUTE_METHOD;
    public static BundleMessage ERROR_OCCURED_MQTT_PUBLISH;
}
